import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.166.1/build/three.module.js";

const $=id=>document.getElementById(id);
const statusEl=$("status"),startBtn=$("start"),goBtn=$("go"),pauseBtn=$("pause"),againBtn=$("again"),flyBtn=$("fly"),winnerEl=$("winner"),errorEl=$("error");
const michaelInput=$("mi"),soldierInput=$("ki"),michaelCountEl=$("mc"),soldierCountEl=$("kc"),michaelBar=$("mb"),soldierBar=$("kb"),michaelTeamPower=$("mtp"),soldierTeamPower=$("ktp");
const MAX_ARMY=1000,SOLDIER_POWER=2.6;

function draftCounts(){return{m:Math.max(0,Math.min(MAX_ARMY,Math.round(Number(michaelInput.value||0)))),k:Math.max(0,Math.min(MAX_ARMY,Math.round(Number(soldierInput.value||0))))}}
function previewPower(){const v=draftCounts();michaelTeamPower.textContent="Team: "+v.m.toFixed(1);soldierTeamPower.textContent="Team: "+(v.k*SOLDIER_POWER).toFixed(1)}
function committedCounts(){const m=Math.max(1,Math.min(MAX_ARMY,Math.round(Number(michaelInput.value||1)))),k=Math.max(1,Math.min(MAX_ARMY,Math.round(Number(soldierInput.value||1))));michaelInput.value=m;soldierInput.value=k;return{m,k}}
michaelInput.addEventListener("input",previewPower);soldierInput.addEventListener("input",previewPower);previewPower();

try{
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x07111f);scene.fog=new THREE.FogExp2(0x07111f,.0065);
  const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,600);camera.position.set(0,42,78);
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.prepend(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xc7eaff,0x28331d,2.15));scene.add(new THREE.AmbientLight(0x415976,.3));
  const sun=new THREE.DirectionalLight(0xffead0,3.2);sun.position.set(-45,70,34);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-110;sun.shadow.camera.right=110;sun.shadow.camera.top=110;sun.shadow.camera.bottom=-110;scene.add(sun);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(260,190,32,24),new THREE.MeshStandardMaterial({color:0x4d6738,roughness:1}));const gp=ground.geometry.attributes.position;for(let i=0;i<gp.count;i++)gp.setZ(i,.2*Math.sin(.08*gp.getX(i))+.16*Math.cos(.07*gp.getY(i)));ground.geometry.computeVertexNormals();ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
  const line=new THREE.Mesh(new THREE.PlaneGeometry(.75,170),new THREE.MeshBasicMaterial({color:0xf3cb60,transparent:true,opacity:.28}));line.rotation.x=-Math.PI/2;line.position.y=.03;scene.add(line);

  const mat={black:new THREE.MeshStandardMaterial({color:0x101218,roughness:.48}),hair:new THREE.MeshStandardMaterial({color:0x17191f,roughness:.56}),white:new THREE.MeshStandardMaterial({color:0xf1f3f4,roughness:.38}),silver:new THREE.MeshStandardMaterial({color:0xbcc4ca,roughness:.24,metalness:.82}),red:new THREE.MeshStandardMaterial({color:0x9b2a34,roughness:.55}),skin:new THREE.MeshStandardMaterial({color:0xd6a079,roughness:.72}),eye:new THREE.MeshStandardMaterial({color:0xf9fbff,roughness:.18}),pupil:new THREE.MeshStandardMaterial({color:0x1e2229,roughness:.1}),lip:new THREE.MeshStandardMaterial({color:0xa35a5c,roughness:.7}),gold:new THREE.MeshStandardMaterial({color:0xe1b348,roughness:.3,metalness:.7}),brown:new THREE.MeshStandardMaterial({color:0x6b4028,roughness:.72}),cloth:new THREE.MeshStandardMaterial({color:0x242833,roughness:.72})};
  const q0=new THREE.Quaternion(),s1=new THREE.Vector3(1,1,1),tmpPos=new THREE.Vector3(),tmpScale=new THREE.Vector3(),tmpEuler=new THREE.Euler(),tmpQuat=new THREE.Quaternion(),tmpLocal=new THREE.Matrix4(),tmpFinal=new THREE.Matrix4();
  function makeInstanced(geometry,material,shadow=false){const mesh=new THREE.InstancedMesh(geometry,material,MAX_ARMY);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.castShadow=shadow;mesh.receiveShadow=shadow;mesh.frustumCulled=false;scene.add(mesh);return mesh}
  function part(geometry,material,pos,rot,role="",shadow=false,scale=null){const p={mesh:makeInstanced(geometry,material,shadow),pos:new THREE.Vector3(...pos),rot:new THREE.Euler(...rot),role,scale:scale?new THREE.Vector3(...scale):new THREE.Vector3(1,1,1)};p.quat=new THREE.Quaternion().setFromEuler(p.rot);p.local=new THREE.Matrix4().compose(p.pos,p.quat,p.scale);return p}
  const box=(x,y,z)=>new THREE.BoxGeometry(x,y,z),cyl=(a,b,h,n=10)=>new THREE.CylinderGeometry(a,b,h,n),sphere=(r,w=12,h=9)=>new THREE.SphereGeometry(r,w,h);

  function michaelParts(){return[
    part(box(1.12,2.04,.7),mat.white,[0,2.6,0],[0,0,0],"",true),part(box(.78,1.5,.73),mat.black,[0,2.53,.02],[0,0,0]),part(box(.84,.12,.72),mat.gold,[0,1.72,.01],[0,0,0]),
    part(sphere(.45,16,12),mat.skin,[0,4.05,0],[0,0,0],"",true),part(sphere(.49,14,10),mat.hair,[0,4.18,-.06],[0,0,0],"",false,[1,.72,.94]),part(cyl(.48,.58,.3,16),mat.black,[0,4.6,0],[0,0,0]),part(cyl(.76,.76,.07,18),mat.black,[0,4.44,0],[0,0,0]),
    part(sphere(.07,9,7),mat.eye,[-.15,4.1,.37],[0,0,0]),part(sphere(.07,9,7),mat.eye,[.15,4.1,.37],[0,0,0]),part(sphere(.03,8,6),mat.pupil,[-.15,4.095,.405],[0,0,0]),part(sphere(.03,8,6),mat.pupil,[.15,4.095,.405],[0,0,0]),part(box(.07,.16,.08),mat.skin,[0,4,.42],[0,0,0]),part(box(.14,.025,.03),mat.lip,[0,3.82,.4],[0,0,0]),
    part(cyl(.14,.16,.78,9),mat.white,[-.78,2.72,0],[0,0,.26]),part(cyl(.14,.16,.78,9),mat.white,[.78,2.72,0],[0,0,-.26]),part(cyl(.11,.13,.82,9),mat.black,[-1.05,2.1,0],[0,0,.08]),part(cyl(.11,.13,.82,9),mat.black,[1.05,2.1,0],[0,0,-.08],"rightArm"),
    part(sphere(.09,8,6),mat.skin,[-1.11,1.67,.02],[0,0,0]),part(sphere(.09,8,6),mat.skin,[1.11,1.67,.02],[0,0,0]),part(cyl(.16,.19,1.78,9),mat.black,[-.22,.88,0],[0,0,0],"leftLeg"),part(cyl(.16,.19,1.78,9),mat.black,[.22,.88,0],[0,0,0]),part(box(.38,.18,.72),mat.white,[-.22,.04,.16],[0,0,0]),part(box(.38,.18,.72),mat.white,[.22,.04,.16],[0,0,0])
  ]}
  function knightParts(){return[
    part(box(1.28,2.08,.78),mat.red,[0,2.56,-.02],[0,0,0]),part(box(1.05,1.54,.86),mat.silver,[0,2.7,0],[0,0,0],"",true),part(box(.9,1.05,.9),mat.cloth,[0,2.52,-.05],[0,0,0]),part(box(.96,.12,.8),mat.brown,[0,1.72,0],[0,0,0]),
    part(sphere(.42,16,12),mat.skin,[0,4.03,0],[0,0,0]),part(sphere(.065,9,7),mat.eye,[-.14,4.08,.36],[0,0,0]),part(sphere(.065,9,7),mat.eye,[.14,4.08,.36],[0,0,0]),part(sphere(.028,8,6),mat.pupil,[-.14,4.075,.395],[0,0,0]),part(sphere(.028,8,6),mat.pupil,[.14,4.075,.395],[0,0,0]),
    part(cyl(.53,.58,.7,14),mat.silver,[0,4.23,0],[0,0,0],"",true),part(box(.62,.08,.18),mat.silver,[0,4.14,.24],[0,0,0]),part(box(.1,.5,.12),mat.silver,[0,4.02,.39],[0,0,0]),
    part(cyl(.64,.64,.13,12),mat.gold,[-.92,2.55,.02],[0,0,Math.PI/2],"shield",true),part(sphere(.1,9,7),mat.silver,[-.98,2.55,.02],[0,0,0]),part(box(.1,2.06,.11),mat.silver,[.95,2.92,0],[0,0,-.34],"sword",true),part(box(.36,.08,.14),mat.gold,[.95,1.98,0],[0,0,0]),
    part(cyl(.15,.18,.94,9),mat.silver,[-.72,2.55,0],[0,0,.08]),part(cyl(.15,.18,.94,9),mat.silver,[.72,2.55,0],[0,0,-.08]),part(cyl(.18,.21,1.8,9),mat.cloth,[-.23,.9,0],[0,0,0]),part(cyl(.18,.21,1.8,9),mat.cloth,[.23,.9,0],[0,0,0]),part(box(.4,.2,.72),mat.brown,[-.23,.04,.12],[0,0,0]),part(box(.4,.2,.72),mat.brown,[.23,.04,.12],[0,0,0])
  ]}

  class CharacterBatch{
    constructor(kind){this.kind=kind;this.parts=kind==="m"?michaelParts():knightParts()}
    update(units,time){const count=units.length;for(let i=0;i<count;i++){const u=units[i],bob=u.alive?(u.knight?Math.abs(Math.sin(time*6+u.phase))*.045:Math.sin(time*8+u.phase)*.055):0;tmpPos.set(u.x,bob,u.z);tmpEuler.set(0,u.knight?-Math.PI/2:Math.PI/2,u.alive?0:(u.fallSide*Math.PI/2*Math.min(1,u.fall)));tmpQuat.setFromEuler(tmpEuler);tmpScale.setScalar(u.scale);u.baseMatrix.compose(tmpPos,tmpQuat,tmpScale)}for(const p of this.parts){for(let i=0;i<count;i++){const u=units[i];if(p.role){tmpEuler.copy(p.rot);const swing=u.attack>0?Math.sin((1-u.attack/.3)*Math.PI):0;if(p.role==="rightArm")tmpEuler.z=p.rot.z-swing*1.05;else if(p.role==="leftLeg")tmpEuler.x=swing*.9;else if(p.role==="sword")tmpEuler.z=p.rot.z-swing*1.45;else if(p.role==="shield")tmpEuler.y=Math.sin(time*2+u.phase)*.05;tmpQuat.setFromEuler(tmpEuler);tmpLocal.compose(p.pos,tmpQuat,p.scale)}else tmpLocal.copy(p.local);tmpFinal.multiplyMatrices(u.baseMatrix,tmpLocal);p.mesh.setMatrixAt(i,tmpFinal)}p.mesh.count=count;p.mesh.instanceMatrix.needsUpdate=true}}
  }
  const michaelBatch=new CharacterBatch("m"),knightBatch=new CharacterBatch("k");
  let mUnits=[],kUnits=[],targetM=50,targetK=10,aliveM=50,aliveK=10,running=false,paused=false,finished=false,flyover=true,simTime=0,flyAngle=0,battleRadius=55,lastFrame=0;
  const flyTarget=new THREE.Vector3(0,3.5,0),desiredCamera=new THREE.Vector3();

  function formation(count,knight){const cols=Math.max(1,Math.ceil(Math.sqrt(count*1.65))),rows=Math.ceil(count/cols),spacingZ=1.12,spacingX=1.12,baseX=knight?8:-8,dir=knight?1:-1,units=[];for(let i=0;i<count;i++){const row=Math.floor(i/cols),col=i%cols;units.push({id:i,knight,x:baseX+dir*row*spacingX,z:(col-(cols-1)/2)*spacingZ+(Math.random()-.5)*.12,hp:knight?17:3.2,alive:true,cooldown:Math.random()*(knight ? .8 : .4),attack:0,hit:0,phase:Math.random()*6.28,fall:0,fallSide:Math.random()<.5?-1:1,scale:knight ? .9 : .86,target:null,retarget:Math.random(),sonic:knight?1e9:2.5+Math.random()*7,master:!knight&&i%6===0,baseMatrix:new THREE.Matrix4()})}battleRadius=Math.max(42,cols*spacingZ*.72+rows*spacingX*.9);return units}

  function chooseTarget(u,enemies){let best=null,bestD=Infinity;const n=enemies.length;if(!n)return null;for(let j=0;j<12;j++){const v=enemies[Math.floor(Math.random()*n)];if(!v.alive)continue;const dx=v.x-u.x,dz=v.z-u.z,d=dx*dx+dz*dz;if(d<bestD){bestD=d;best=v}}if(best)return best;for(let j=0;j<n;j++){const v=enemies[(u.id+j)%n];if(v.alive)return v}return null}
  function damage(target,amount){if(!target||!target.alive)return;target.hp-=amount;target.hit=.18;if(target.hp<=0){target.alive=false;target.fall=.02;if(target.knight)aliveK--;else aliveM--;updateHud()}}
  function sampleNearby(attacker,enemies,radius){for(let j=0;j<10;j++){const v=enemies[Math.floor(Math.random()*enemies.length)];if(!v||!v.alive||v===attacker)continue;const dx=v.x-attacker.x,dz=v.z-attacker.z;if(dx*dx+dz*dz<=radius*radius)return v}return null}
  function attackUnit(u,target,enemies){u.attack=.3;if(u.knight){u.cooldown=.9+Math.random()*.28;if(Math.random()<.9)damage(target,.95+Math.random()*.26);if(Math.random()<.22){const second=sampleNearby(target,enemies,2.2);if(second)damage(second,.45+Math.random()*.2)}}else{const master=u.master;u.cooldown=(master ? .3 : .43)+Math.random()*(master ? .22 : .25);if(Math.random()<(master ? .93 : .87))damage(target,(master?1.2:.95)+Math.random()*(master ? .42 : .3));if(master&&Math.random()<.2){const second=sampleNearby(target,enemies,1.9);if(second)damage(second,.4+Math.random()*.2)}}}
  function heeHee(u){u.sonic=5+Math.random()*5;statusEl.textContent="Hee hee shockwave rattles the medieval line!";for(let i=0;i<3;i++){const v=sampleNearby(u,kUnits,6);if(v){v.cooldown+=.3;damage(v,.35+Math.random()*.16)}}}

  function updateSide(units,enemies,dt){for(const u of units){if(!u.alive){u.fall=Math.min(1,u.fall+dt*2.4);continue}u.cooldown-=dt;u.attack=Math.max(0,u.attack-dt);u.hit=Math.max(0,u.hit-dt);u.retarget-=dt;if(!u.knight)u.sonic-=dt;if(!u.target||!u.target.alive||u.retarget<=0){u.target=chooseTarget(u,enemies);u.retarget=.45+Math.random()*.7}const t=u.target;if(!t)continue;const dx=t.x-u.x,dz=t.z-u.z,dist=Math.hypot(dx,dz),range=u.knight?2.45:1.45;if(!u.knight&&u.master&&u.sonic<=0)heeHee(u);if(dist>range){const speed=u.knight?4.1:(u.master?5.5:5.0),inv=dist>0?1/dist:0;u.x+=dx*inv*speed*dt;u.z+=dz*inv*speed*dt;u.z+=Math.sin(u.id*1.71+simTime*.8)*.002}else if(u.cooldown<=0)attackUnit(u,t,enemies)}}
  function step(dt){updateSide(mUnits,kUnits,dt);updateSide(kUnits,mUnits,dt);if(aliveK<=0)finish("🕺 MICHAEL JACKSON ARMY WINS!");else if(aliveM<=0)finish("⚔️ MEDIEVAL ARMY WINS!")}
  function updateHud(){michaelCountEl.textContent=String(aliveM);soldierCountEl.textContent=String(aliveK);michaelBar.style.width=(aliveM/Math.max(1,targetM)*100)+"%";soldierBar.style.width=(aliveK/Math.max(1,targetK)*100)+"%"}
  function finish(text){finished=true;running=false;winnerEl.textContent=text;winnerEl.style.display="block";statusEl.textContent="Battle complete"}
  function resetBattle(m=targetM,k=targetK){targetM=m;targetK=k;aliveM=m;aliveK=k;running=false;paused=false;finished=false;simTime=0;flyAngle=0;winnerEl.style.display="none";pauseBtn.textContent="Pause";mUnits=formation(m,false);kUnits=formation(k,true);battleRadius=Math.max(battleRadius,Math.sqrt(m+k)*1.6);michaelBatch.update(mUnits,0);knightBatch.update(kUnits,0);updateHud();startBtn.hidden=false;statusEl.textContent="Ready — "+(m+k).toLocaleString()+" physical characters rendered";renderer.setPixelRatio(Math.min(devicePixelRatio,m+k>1200 ? .9 : m+k>700 ? 1 : 1.2));renderer.setSize(innerWidth,innerHeight)}
  function startBattle(){startBtn.hidden=true;running=true;paused=false;finished=false;statusEl.textContent="Battle running — "+(targetM+targetK).toLocaleString()+" physical characters on the field"}

  goBtn.onclick=()=>{const v=committedCounts();previewPower();resetBattle(v.m,v.k);startBattle()};startBtn.onclick=startBattle;againBtn.onclick=()=>resetBattle(targetM,targetK);pauseBtn.onclick=()=>{if(finished)return;paused=!paused;pauseBtn.textContent=paused?"Resume":"Pause";statusEl.textContent=paused?"Battle paused":"Battle running — full physical armies"};flyBtn.onclick=()=>{flyover=!flyover;flyBtn.className=flyover?"on":"";flyBtn.textContent=flyover?"Flyover ON":"Flyover OFF";statusEl.textContent=flyover?"Cinematic flyover enabled":"Fixed battle view enabled"};
  addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});

  const clock=new THREE.Clock();
  function updateCamera(dt){const alive=[...mUnits,...kUnits].filter(u=>u.alive);if(alive.length){let sx=0,sz=0;for(const u of alive){sx+=u.x;sz+=u.z}flyTarget.x+=(sx/alive.length-flyTarget.x)*.04;flyTarget.z+=(sz/alive.length-flyTarget.z)*.04}if(flyover){flyAngle+=dt*.18;const radius=battleRadius+10+Math.sin(flyAngle*1.7)*6,height=Math.max(28,battleRadius*.48)+Math.sin(flyAngle*.75)*8;desiredCamera.set(flyTarget.x+Math.cos(flyAngle)*radius,height,flyTarget.z+Math.sin(flyAngle)*radius*.85);camera.position.lerp(desiredCamera,.035)}else{desiredCamera.set(0,Math.max(42,battleRadius*.72),battleRadius+35);camera.position.lerp(desiredCamera,.04)}camera.lookAt(flyTarget.x,3.2,flyTarget.z)}
  function frame(now){requestAnimationFrame(frame);let dt=Math.min(clock.getDelta(),.05);const total=targetM+targetK,interval=total>1400?1000/24:total>750?1000/30:0;if(interval&&now-lastFrame<interval)return;lastFrame=now;if(running&&!paused&&!finished){simTime+=dt;step(dt)}else{for(const u of mUnits)if(!u.alive)u.fall=Math.min(1,u.fall+dt*2.4);for(const u of kUnits)if(!u.alive)u.fall=Math.min(1,u.fall+dt*2.4)}michaelBatch.update(mUnits,simTime);knightBatch.update(kUnits,simTime);updateCamera(dt);renderer.render(scene,camera)}

  resetBattle(50,10);requestAnimationFrame(frame);
}catch(error){statusEl.style.display="none";startBtn.hidden=true;errorEl.style.display="block";errorEl.textContent="The 3D battle could not load. Reload in Safari. Details: "+error.message}
